name: invitation_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
  
  fonts:
    - family: BrushScriptMT
      fonts:
        - asset: fonts/Brush-Script-MT-Regular.ttf
    - family: Upakarti
      fonts:
        - asset: fonts/Upakarti-Regular.ttf
        - asset: fonts/Upakarti-Italic.ttf
          style: italic
